### ISSUE TITLE
Submit button

### ISSUE THREAD

**Issue by holly-johnson** [KayleeZnamenacek/kaylee-portfolio-site#11]
Shouldn't be this wide on large. 

<img width="733" alt="Screen Shot 2020-04-30 at 10 13 54 PM" src="https://user-images.githubusercontent.com/15253544/80780240-df0d3880-8b33-11ea-82b7-99942109b2b5.png">

**Comment by KayleeZnamenacek** [comment]
fixed this! it's this length only at small display now.
