### ISSUE TITLE
Mobile: Back/Next Button Styles

### ISSUE THREAD

**Issue by holly-johnson** [KayleeZnamenacek/kaylee-portfolio-site#13]
Here's what I did in dev tools (see left for code) - is this what you were going for? I would have the arrow smaller and adding space between.

<img width="1008" alt="Screen Shot 2020-05-10 at 8 33 23 PM" src="https://user-images.githubusercontent.com/15253544/81516464-9147bb80-92fd-11ea-9caf-b3b1883d32bc.png">

**Comment by KayleeZnamenacek** [comment]
Yes! I will play around with that code to see if it'll work. Thank you!

**Comment by KayleeZnamenacek** [comment]
I forgot a closing } ugh once I figured out where it was this fixed itself.
